### ISSUE TITLE
Green Images while training

### ISSUE THREAD

**Issue by neosr-project** [mandalinadagi/WGSR#3]
Hi, thanks for your research. I'm trying to port your paper code, but it looks like the loss is causing a hue shift on all images towards green. Any idea why?

![wgsr_green](https://github.com/mandalinadagi/WGSR/assets/132400428/ab7e1963-0e96-413a-94aa-44da37822b48)

I'm using the default values for each band (0.1, 0.01, 0.01, 0.05), and the implementation of SWT is unchanged.

**Comment by mandalinadagi** [comment]
This color shift towards green generally happens when feature loss is not utilized. Since SWT losses are calculated on Y channels unless the other losses are used with proper weights, SWT losses dominate training and cause such greenish colors to get exaggerated. So please check RGB L1 loss, feature loss and their weights

**Comment by neosr-project** [comment]
It works now, thanks :+1:
